language: node_js
node_js:
- stable
before_install:
- sudo pip install virtualenv
- virtualenv my_project
- source my_project/bin/activate
before_script:
- npm install -g gitbook-cli
script: bash ./deploy.sh
after_success:
- rm -rf _book/my_project
- pip install git+https://github.com/dtolb/s3-deploy-website.git
- s3-deploy-website "docs"
env:
  global:
  - ENCRYPTION_LABEL: 044ee5d239db
  - COMMIT_AUTHOR_EMAIL: developerhelp@bandwidth.com
  - secure: KxTPq5npXk5AHGOX130LGnVIeIJxaG50B9mKsal300KFoNNc+GWiFOMrRtgwCtY3jVO6GL680WwYjL/CdLoM48/pvH27wusEe0ak7SAd88Lhpr58l+GEHmB7ru0pBBsLvYb1oUHMBBRJgtCz0+5VOUEiX2p063eC8eItmjmkO0CZjTPuI2AprKS0urSI0afjpop3imzC7RRUKxEzFXCGmhjS/FCvkE41flEsxBfjutohm8ruChriswyiADSUc5YEbgblfavMlmyI9ebp2AS7flhpe88/C8hFEb67NQwvjmI1D36uQ3k5Sg94O4Brl3D8AJTP9r/7MSR8tO7XBzJRcsppCWNbEJCRw39lk1e5HOENp78yv0qwjvYBUQCG97FGZGCSmppVjYqxE7Zsw5hfOvz7J+2RvJDb7DO0hpPD/YdVt+M/GihBLVPXb+T/hrbg6wHNGnx3SeGANlCVDUT2s8dTrIY2yPPSIo7xr9uXOLs3X6+QYuKSc2GuJBZPbKZw+PWkKnGSvwfj6CncRpPHIyUJkoaNEHhBG+B9Z3y49QfPT1J1MtnSa9yHJNQPdI5v8YHZ3lr+ZjNMILyUpLOgsAQB41uExZ6P7GU/nlJlhmBhK2zAiJ2QGSU5L84PvE35zKZH2aVc9shk/CUvEjzFgQMW/vFfozCDZLTlL3IzwR8=
  - secure: L+mMaH6wlUWhzth0qlevi8AI1/R2QDak5jv9NE687qbMlNPVOXYguhQmA2P+MG4X9IZ15KT4QDjjyl60sl1TK8fUZkBMmM0a9MH3/k/qhhahvnxpHY/otbgaSSuJAYHcemNeR/41mYJXul9gR/ONfhXW9VNdwQkerFT9OBfg+9FmF/FA4UlNpCceAhjiFhODuuKEtti3BeY3sNO404sKaNAjYNM4yboM2gi0r8+Glh6iGCgCrvZ+WHrfCoPYoJD4nGHP4+x7IKEJeaAXXo/c6sKwows1f78h/cgW7GwGAbbZ84t67wlEIuCbg3h9P7DXWzLW6Ryl8htSmfZT1eCQzOXKPZiL3Bf3MeUyinU3KeQ3Ff/x3nLKCZizCYruPY89RvcScjQJ+jj1UtChrq9g0nI9Gu+wcHdewBwCYbKXLPR49ON9OZNuspvaKtBHO+CqNVqczkq19RNBSDUhML2s/fQLNnyYbVVYEgFo8HybMsNA/IkEvt0+nr7pVTx0bj9ZAAIVJuuXE94haMacsqF1/MiE1S2HXGkZlyZ5HFFcOlpQ5uzDFPJKIlWWnA2P10N+PCPGuiXU2gmro7SGNPmoVJ5q/9A/TaNk0ukGdSxxTmQ3Jpqm8g50ZsONMbtyupb/A5nc658OtY34XQvj6bvPRKWXdtB5b8qWhW1KM4+P41E=
  - secure: dMWsNfU+I5Ol9y5CBcOUH10Int/BHy2KmGhSyUfERG8ggw1OVoh71v4iMiyVUAY27jXGC5Wqn89DiEqudyF+sQ+B3GOJcNAUFfDu99x9AOeFDaesQ9QaZC0exXVf0kJIKXOM7EdnSt5cmRXdvfRMvej645GPh5CyHjmH/f8x7dHY+DLMZbDfbPdEM3AOyeejBTA7XXNnL3hJduwZ0YSTmK0z8A6fgtH9vfIkeIM0K7NyFG+W0tF0HavxkP92Z+Ryw3l1FtX5tqvctouKdbNC2u1DJJ3nlwrmTJeNsYGRfkURGzkicScp6C4Kuy8boD12acyPpGDO3LHyKiEuG1DWF9/D7PkDN2XvzykXKa67/hwGiTkN7sbi6Ue289bsEnHT3JXOllr7nIxm3dKt0FZi8tt6s744uxQxHH7C9XizmxLPjLUO6ya6TWlU2OkyLkSXOOtANXlX0QncRzWXpP1z0Jd4QxZDpQtVyA78a/up1bnaFjqMke0BZR283bJcFVhc3tP6Ktmz9and9+o1cuwuS3v2DrqOTBrvd3IYb7aYmW+uErqG5HlWNaYmgZGMz0A3qmcFnE6Nb0QwIwxv+HIHHmIo8Eo8UnfT2HkeBc3L5IFy4/VOk+wQYQ15MDbwcSgF1vAuVbfIYy8oI3T0WtVuTiUvSMG9BqkoO/4+U2/x5TM=
