language: node_js
node_js:
- stable
before_install:
- sudo pip install virtualenv
- virtualenv my_project
- source my_project/bin/activate
before_script:
- npm install -g gitbook-cli
script: bash ./deploy.sh
after_success:
- rm -rf _book/my_project
- pip install git+https://github.com/dtolb/s3-deploy-website.git
- s3-deploy-website "docs"
env:
  global:
  - ENCRYPTION_LABEL: 044ee5d239db
  - COMMIT_AUTHOR_EMAIL: dtolb@bandwidth.com
  - secure: tf0fC2EvmzVNGDqwUMYV/8t1UJxicILVrKmeJjvPhNVkelsfmPkX9JXK6wNRZjdMjtgejBQXvNO0Fcne6habf5M/yx9i6gYES7HrJk1B1soDPqphKJqDXfIqWW5OXr3yNfmAqi20P4N8QRfjOnnZnkX6HSmhm5uU5UFX8AXVOxIOfYsHNQdUaedpNqr8BbP+YVYKeyUsxP54n+t2tDB12ytyVMWlsaa3mPURuwPFVDwePQ1C6nTQCDDt8wpwd7xul3ABnEMx4TRZ0ExTq/aCj7dP/whuv1TP289vmuozNysKoM9uw3MotFxnpcy5TTiVyJz2sjxYJCVORjX+XvhmcZkvj6MkhR9VxjmBN4G6wmAy07DjF2eQQaBis6MelMVTKIqdgzwpveNmKV91kjWR+fjpDIwA7eyCZ/WiotEa4XsmT0NtlsFeeEKB+wgeR66JXsy4lMc1OpYUWKiMSy8KCRFf6z0wjUbFlzqa6EIyT/SOWBb7a7j1Ke6kF/fj7EueWWREXrUOcsEffwlQ4vBm31ZBduWVR+Pd2CADGMw5lzBBNVUzBkzrF5W+tXSkPJT41/2MYbOa2MJMCZi6PZbgOR2EsMyt2jU/9oTmHaeHoMbS4bKaAXG5OPlzy9U/P7R3HQ4MX6agVkNeya0lAJI8EdNbLSOoySOcpt19Yl+EPT4=
  - secure: JUnD6vsCK1Af2v605QLpKksDfKKka/1/SeOWPhx9y5UC5zmUnUv0fI8Y2uVqObfSuMcTrhLHWc343KYPiC6V+kMXgvQCyveE+7URLkN82z3WM5MuYu8Pyf70tfiElTZ/M11MPQu2CWNZQvEk9xi16k3Bwowhm4HcdjKZNkwOp+klD3auw71/9Kc4Ik3hZTIocvjrsSvqkB5XdehvXGpFaI/YBqkNQ2ns8bx7o9vqsbP44jG4dIC5rwgLS70Ca9TSrwR9dzFu/RiodJnW1Hd2eLvgDzU9NxTYb+ycgWSG5QbjEpyhC+BbDQfT8ot523yC29MBNQaxn05yBDC577M4mBGeeNygkXblLEm5yap7BlgTpn6ic28Z+t0yjrIOF0wAqMHZ+BUmavBlgZKZzeSqzDyR+tVPIIGSET1fSmwFJ+ubCaJWDIfjMDC1lNdFOL5JD0PtwhLHaMIOKD9dTfmNTIPQfT/QVAIyJfd5vNaoFnrZz43Rv0K3TAo6LsCJlhmTEvQLjOZlmWms+9cNMFY1OFCFAjOrt3R297e0Aq6IhqOEbx/u4qLqPiH53hyNIcn3AteNSszHlhtV31ERiF93bZmUwazq7Yga4rEjhNtJ+3Qlm3QmP2Mw3XJhUW3PPujVYInapTUgDw7ayUzAtuFxtLizE1szdfnHPghbQIqFLUk=
  - secure: XBtOr1Ar0moc6nSPxS6vcWvUX/T8yK0DqFU/LPiNqkephg4a0rC2w1VSBcfZgwTioKwL+y8tCPW4uAxjleRAVuDfonAThFK6/p2KHXqfeuSWtRWksZSau5PcVC/HOqfgHyT/geFfthTZLCXrQ8ygpYEjQx2DYx6ihYVMtQfAo8FRj2RMg+hgmyDbyaONGDbQAr98ZEN8E+pNoBqcNJbCoF+8uuaG9TKvMbcLA9vRnBimFmS/7UVG/Qinm+4BcCLH2bv88ViikjBFLXB8DsIokro/cU1GW+YEVU2tlv7u2L9qnKCTbu4xKSfZvGwsTAHGqgepPCztgMNMAbNTpQFWJP+QmvyS42R6anB/MpDQWVn1woeAgzDlwv7UrQoSrXhnS6dBe3M/pbheHHInWsD3+EnQLB14CCXBiFt2n1JXKVJX22yAg2oUlLjQIUrHW/IT0ZAtfgyK3Mjy+H3tckqOSjFKe6RKds5LkqJ2qoDD10InnmtjwBGCAFobCX+mJeAUMrCcUflYWIRAcm2Q/OPHWPrZhuz2aWgTJ/ymafanD80yLByN6qg7HiaRhSafvR106kOeWxFRiHWS6Y+skCFl3flDfqYyR2n/UPGkV7SmXAXx15xko0h2N7C5NMfoFuF7R2tYM1jWakf6nkvHzozEI2gsHALJJW1SdHUtiF/6ld8=
